# Example Horizontal Pod Autoscaler (HPA)
# Could be disabled or enabled as needed. For now, it’s just a placeholder.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "toy-service.fullname" . }}
  labels:
    app: {{ include "toy-service.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "toy-service.fullname" . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80