{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "toy-service.fullname" . }}
  labels:
    app: {{ include "toy-service.name" . }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "toy-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}