services:
  toy-service:
    name: toy-service
    repository: quay.io/paulcapestany/toy-service
    tag: v0.2.24-commit.853db03
    replicaCount: 1
    ingress:
      enabled: true
      hostname: toy-service-dev.bitiq.io
    hpa:
      enabled: false

  toy-web:
    name: toy-web
    repository: quay.io/paulcapestany/toy-web
    tag: v0.1.0-commit.abc1234
    replicaCount: 1
    ingress:
      enabled: true
      hostname: toy-web-dev.bitiq.io
    hpa:
      enabled: false
