services:
- name: toy-service
  repository: quay.io/paulcapestany/toy-service
  tag: v0.2.14-commit.f85a921
  replicaCount: 1
  ingress:
    enabled: true
    hostname: toy-service-dev.bitiq.io
  hpa:
    enabled: false
services[0]:
  tag: v0.2.15-commit.61f632e
  repository: quay.io/paulcapestany/toy-service
