# Global defaults for all bitiq services.
# These can be overridden by environment-specific values files.
global:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  servicePort: 8080

# Dictionary of services deployed by this chart.
# Keys are service names, values are service configurations.
services:
  toy-service:
    name: toy-service
    repository: quay.io/paulcapestany/toy-service
    tag: v0.1.0-abc1234
    replicaCount: 1
    ingress:
      enabled: false
      hostname: toy-service.bitiq.io
    hpa:
      enabled: false
# Use external secrets if needed
extraEnv: []