services:
  toy-service:
    name: toy-service
    repository: quay.io/paulcapestany/toy-service
    # the tag below is updated by Argo CD Image Updater
    tag: v0.2.12-commit.7a4bc53
    replicaCount: 2
    ingress:
      enabled: true
      hostname: toy-service-prod.bitiq.io
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      cpuTargetUtilization: 80