services:
  toy-service:
    name: toy-service
    repository: quay.io/paulcapestany/toy-service
    tag: v0.2.20-commit.334a36b
    replicaCount: 1
    ingress:
      enabled: true
      hostname: toy-service-dev.bitiq.io
    hpa:
      enabled: false
