apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: default
type: Opaque
stringData:
  # Replace the below with your actual GitHub webhook secret
  secret: "REPLACE_WITH_ACTUAL_SECRET"