apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: toy-service-build-template
  namespace: default
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: fullSha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: toy-service-build-run-
      spec:
        serviceAccountName: pipeline-sa
        pipelineRef:
          name: toy-service-build-pipeline
        params:
          # The git revision is expected to be in a format like "refs/heads/main"
          # We'll ensure we only trigger if this matches main below via interceptor.
          - name: git-url
            value: "$(tt.params.git-url)"
          - name: git-revision
            value: "$(tt.params.git-revision)"
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
        podTemplate:
          securityContext:
            fsGroup: 65532                    