apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: toy-service-prod
  labels:
    app.kubernetes.io/part-of: toy-service
    environment: prod
  annotations:
    # NOTE: argocd-image-updater annotations requre the service alias to only by alphanumeric characters (e.g. no hyphens)
    argocd-image-updater.argoproj.io/image-list: "toyservice=quay.io/paulcapestany/toy-service:>0.2.0"
    argocd-image-updater.argoproj.io/toyservice.update-strategy: "semver"
    argocd-image-updater.argoproj.io/toyservice.versionConstraint: ">0.1.0-0"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:values-prod.yaml"
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/toyservice.helm.image-name: services['toy-service'].repository
    argocd-image-updater.argoproj.io/toyservice.helm.image-tag: services['toy-service'].tag
spec:
  project: default
  source:
    repoURL: 'https://github.com/paulcapestany/gitops.git'
    path: 'helm/bitiq'
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true