apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-workspace
  namespace: default
spec:
  workspaces:
    - name: source
      description: "Workspace containing the source code and where we will create directories"
      mountPath: "/workspace/source"
  steps:
    - name: prepare-workspace
      image: alpine:3.17
      securityContext:
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -xe
        mkdir -p /workspace/output/gitops
        chmod 777 /workspace/output/gitops