apiVersion: v1
kind: Secret
metadata:
  name: quay-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKERCONFIG_JSON> # echo -n '{"auths":{"quay.io":{"username":"paulcapestany","password":...}}' | base64