apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests-task
  namespace: default
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: alpine:3.17
      script: |
        set -xe
        apk add --no-cache curl bash tar openssl git
        
        # Install Helm
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
        # Install helm unittest plugin
        helm plugin install https://github.com/helm-unittest/helm-unittest
        
        # Install kubeconform
        curl -L https://github.com/yannh/kubeconform/releases/download/v0.4.13/kubeconform-linux-amd64.tar.gz | tar xz
        mv kubeconform /usr/local/bin/kubeconform

        # Helm lint
        helm lint /workspace/source/gitops/helm/bitiq

        # Template and validate with kubeconform
        helm template dev /workspace/source/gitops/helm/bitiq -f /workspace/source/gitops/helm/bitiq/values-dev.yaml > dev-rendered.yaml
        helm template prod /workspace/source/gitops/helm/bitiq -f /workspace/source/gitops/helm/bitiq/values-prod.yaml > prod-rendered.yaml
        kubeconform -strict -ignore-missing-schemas dev-rendered.yaml
        kubeconform -strict -ignore-missing-schemas prod-rendered.yaml

        # Helm unittest
        helm unittest /workspace/source/gitops/helm/bitiq