apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: transform-sha-task
  namespace: default
spec:
  params:
    - name: fullSha
      type: string
  results:
    - name: shortSha
  steps:
    - name: shorten-sha
      image: alpine:3.17
      script: |
        set -xe
        SHORT_SHA=$(echo "$(params.fullSha)" | cut -c1-7)
        printf "%s" "$SHORT_SHA" > $(results.shortSha.path)