apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-events-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-events-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: default
roleRef:
  kind: Role
  name: pipeline-events-role
  apiGroup: rbac.authorization.k8s.io