{{- /*
Iterate over services as a dictionary.
*/ -}}
{{- range $name, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitiq.fullname" $ }}-{{ $name }}
  labels:
    {{- include "bitiq.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/service-version: "{{ $name }}-{{ $service.tag }}"
spec:
  replicas: {{ $service.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $service.repository }}:{{ $service.tag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $.Values.global.servicePort }}
          resources:
            requests:
              cpu: {{ $.Values.global.resources.requests.cpu }}
              memory: {{ $.Values.global.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.global.resources.limits.cpu }}
              memory: {{ $.Values.global.resources.limits.memory }}
{{- end }}