{{- range $name, $service := .Values.services }}
{{- if $service.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitiq.fullname" $ }}-{{ $name }}
  labels:
    {{- include "bitiq.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/service-version: "{{ $name }}-{{ $service.tag }}"
spec:
  rules:
    - host: {{ $service.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bitiq.fullname" $ }}-{{ $name }}
                port:
                  number: {{ $.Values.global.servicePort }}
{{- end }}
{{- end }}