{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitiq.fullname" $ }}-{{ $name }}
  labels:
    {{ include "bitiq.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/service-version: "{{ $name }}-{{ $service.tag }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.global.servicePort }}
      targetPort: {{ $.Values.global.servicePort }}
      name: http
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}