apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-git-credentials
  namespace: openshift-gitops
type: Opaque
data:
  git_token: YOUR_GITHUB_PERSONAL_ACCESS_TOKEN_BASE64_ENCODED # echo -n "ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" | base64