apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: openshift-gitops
data:
  config: |
    git:
      writeBackMethod: "git"
      user: "paulcapestany"
      email: "capestany@gmail.com"
      tokenRef:
        name: argocd-image-updater-git-credentials
        key: git_token