apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-creds
  namespace: openshift-gitops
  labels:
    # This label tells Argo CD that this secret is a repository credential
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  # Base64-encode these values:
  # echo -n "https://github.com/paulcapestany/gitops.git" | base64
  url: aHR0cHM6Ly9naXRodWIuY29tL3BhdWxjYXBlc3RhbnkvZ2l0b3BzLmdpdA==
  # If you're using a personal access token, you can either:
  #   - Use username=personal access token's username (often 'token') and password=PAT
  # or
  #   - Just set the 'password' field and leave username empty if PAT is supported alone
  #
  # For GitHub PATs, you can use username=git (recommended by GitHub)
  # echo -n "PaulCapestany" | base64
  username: UGF1bENhcGVzdGFueQ==
  # echo -n "<YOUR_GITHUB_PERSONAL_ACCESS_TOKEN>" | base64
  password: xxxxxxxxxxxxxx==