apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toy-service-dev
  labels:
    app.kubernetes.io/part-of: toy-service
    environment: dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: "toy-service=quay.io/paulcapestany/toy-service"
    # The image tags should look like: <semver>-<sha>, e.g. v0.1.0-abc1234
    argocd-image-updater.argoproj.io/toy-service.update-strategy: "semver"  
    # This ensures that pre-release versions (like those with -abc1234) are considered for updates
    argocd-image-updater.argoproj.io/toy-service.versionConstraint: ">0.1.0-0"
    argocd-image-updater.argoproj.io/write-back-method: "git"
spec:
  project: default
  source:
    repoURL: 'https://github.com/paulcapestany/gitops.git'
    path: 'helm/toy-service'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true